name: standalone
on:
  workflow_dispatch:
    inputs:
      profile:
        description: EAS build profile (apk/aab)
        required: true
        default: apk
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Start EAS build
        run: >
          npx eas-cli
            --wait
            --platform=android
            --profile=${{ github.event.inputs.profile }}
